# ruby/Gemfile
source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/etc/#{repo_name}" }

gem 'nokogiri', '~> 1.15'
gem 'httparty', '~> 0.21'
gem 'json', '~> 2.6'

group :test do
  gem 'rspec', '~> 3.12'
end
