# libraries/ruby/fastlane/Fastfile
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(
      build_number: ENV["BUILD_NUMBER"]
    )
    build_app(
      workspace: "PolyglotApp.xcworkspace",
      scheme: "PolyglotApp"
    )
    upload_to_testflight
  end

  desc "Run test suite"
  lane :test do
    run_tests(scheme: "PolyglotAppTests")
  end
end
