apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: polyglot-app-template-dev

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: polyglot-app-template
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: polyglot-app-template:dev

configMapGenerator:
  - name: polyglot-app-template-config
    behavior: merge
    literals:
      - APP_LOG_LEVEL=DEBUG
