apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-repo-template
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: dev-repo-template.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-repo-template
                port:
                  number: 80
