apiVersion: v1
kind: Service
metadata:
  name: dev-repo-template
  labels:
    app: dev-repo-template
spec:
  selector:
    app: dev-repo-template
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
