apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-repo-template-dev

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: dev-repo-template
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: dev-repo-template:dev

configMapGenerator:
  - name: dev-repo-template-config
    behavior: merge
    literals:
      - APP_LOG_LEVEL=DEBUG
